name        : PIEA
description : The MiNET plugins development organization.
baseurl     : ''
markdown    : kramdown
highlighter : pygments

disqus_shortname        : "PIEA"
disqus_site_shortname   : "piea"

url: "https://piea.github.io/"

paginate: 3

gems: [jekyll-paginate]