# Setup
title:        PIEA
tagline:      The MiNET plugins development organization.
baseurl:      ""
paginate:     3

# About/contact
author:
  name:       PIEA
  url:        https://piea.github.io

# Gems
gems:
  - jekyll-paginate

# Others
markdown: kramdown

# Disqus
disqus_shortname        : "PIEA"
disqus_site_shortname   : "piea"